struct: "tests/data/NaCl.cif"
min_volume: 0.9
max_volume: 1.1
n_volumes: 10
eos_type: birchmurnaghan
minimize: True
minimize_all: True
fmax: 0.01
minimize_kwargs:
  write_results: True
write_structures: True
arch: mace_mp
device: cpu
model_path: "tests/models/mace_mp_small.model"
read_kwargs:
  index: "0"
calc_kwargs:
  dispersion: True
file_prefix: eos
log: eos.log
summary: eos.yml